import { useState, useEffect } from 'react';
import Head from 'next/head';
import Menu from '../parts/Menu';
import Header from '../parts/Header';
import Monitor from '../parts/Monitor';
import Volume from '../parts/Volume';

export default function Home() {
  const [newData, setNewData] = useState([]);
  const [numberChart, setNumberChart] = useState();

  useEffect(() => {
    handleRepeat();
  }, []);

  // setInterval(() => {
  //   handleRepeat();
  // }, 10000);

  let data = [];

  let name = [
    'Debit',
    'TSS',
    'pH',
    'NO3N',
    'P04',
    'NH3N',
    'TDS',
    'BOD5',
    'COD',
    'Fe',
    'Cu',
    'Cr',
  ];
  let volume = [
    'm3/s',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
  ];

  for (let i = 0; i < name.length; i++) {
    data.push({
      id: i,
      name: name[i],
      volume: volume[i],
      value: [Math.floor(Math.random() * 100)],
    });
  }

  function handleRepeat() {
    data.map((item) => {
      item.value.push(Math.floor(Math.random() * 100));
    });

    setNewData(data);
  }

  const handleClick = (number) => {
    setNumberChart(number);
  };

  return (
    <>
      <Head>
        <title>Dashboard Pupuk Palembang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col w-full h-auto bg-gray-200 pb-8">
        <Header />
        <Menu />

        <Monitor data={newData} numberChart={numberChart} />
        <Volume data={newData} handleClick={handleClick} />
      </main>

      <footer className="flex w-full h-12 justify-center items-center border-t-4">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Pupuk Palembang
        </a>
      </footer>
    </>
  );
}
