import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Menu from '../parts/Menu';
import Header from '../parts/Header';
import Monitor from '../parts/Monitor';
import Volume from '../parts/Volume';
import LeftMonitor from '../parts/LeftMonitor';
import RightMonitor from '../parts/RightMonitor';

export default function Home() {
  const [dataBaru, setDataBaru] = useState([]);
  const [numberChart, setNumberChart] = useState();

  useEffect(() => {
    handleRepeat();
  }, []);

  setInterval(() => {
    handleRepeat();
  }, 10000);

  let data = [];

  let name = [
    'Debit',
    'TSS',
    'pH',
    'NO3N',
    'P04',
    'NH3N',
    'TDS',
    'BOD5',
    'COD',
    'Fe',
    'Cu',
    'Cr',
  ];
  let volume = [
    'm3/s',
    'mg/L',
    null,
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
    'mg/L',
  ];

  for (let i = 0; i < name.length; i++) {
    data.push({
      id: i,
      name: name[i],
      volume: volume[i],
      value: Math.floor(Math.random() * 100),
    });
  }

  function handleRepeat() {
    data.map((item) => {
      item.value = Math.floor(Math.random() * 200);
    });

    setDataBaru(data);
  }

  const handleClick = (number) => {
    setNumberChart(number);
  };

  return (
    <div className="container">
      <Head>
        <title>Dashboard Pupuk Palembang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex flex-col w-full h-auto bg-gray-200 pb-8">
        <Menu />
        {/* <selection>
          <div className="flex flex-row justify-between max-w-7xl mx-auto pt-16 gap-x-8">
            <LeftMonitor data={data} />
            <RightMonitor data={data} />
          </div>
        </selection> */}
        <Monitor data={dataBaru} numberChart={numberChart} />
        <Volume data={dataBaru} handleClick={handleClick} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
